edit text to <user.prose>$: user.ai_edit_selection(prose)
edit code to <user.prose>$: user.ai_edit_code_selection(prose)
query text with <user.prose>$: user.ai_query_selection(prose)
help query active <user.prose>$: user.ai_query_active_commands(prose)
ai chat: user.ai_chat_enable()
ai chat close: user.ai_chat_disable()
