volume up: key(volup)
volume down: key(voldown)
set volume <number>: user.media_set_volume(number)
(volume | media) (mute | unmute): key(mute)
[media] play next | track next: key(next)
[media] play previous | track (last | preev): key(prev)
(media | track) (play | pause): user.play_pause()
