import json
import logging
import re
import time
import uuid
from typing import Optional

from talon import Context, Module, actions, clip, settings, ui

mod = Module()
mod.setting(
    "emacs_meta",
    type=str,
    default="esc",
    desc="""What to use for the meta key in emacs. Defaults to 'esc', since that should work everywhere. Other options are 'alt' and 'cmd'.""",
)

mod.apps.emacs = "app.name: Emacs"
mod.apps.emacs = "app.name: emacs"
mod.apps.emacs = "app.name: /^GNU Emacs/"
mod.apps.emacs = """
os: mac
app.bundle: org.gnu.Emacs
"""
mod.apps.emacs = r"""
os: windows
app.exe: /^emacs\.exe$/i
"""
mod.apps.emacs = "title: /Emacs editor/"

ctx = Context()
ctx.matches = "app: emacs"

DICTATION_PEEK_PROTOCOL_VERSION = 1
DICTATION_PEEK_REQUEST_TYPE = "dictationPeekRequest"
DICTATION_PEEK_RESPONSE_TYPE = "dictationPeekResponse"
DICTATION_PEEK_MINIMUM_SLEEP_SECONDS = 0.0005


class DictationPeekProtocolError(Exception):
    """The Emacs dictation peek response did not match the request."""


def _set_transient_clipboard_text(text: str):
    """Set clipboard text while discouraging clipboard-manager persistence."""
    try:
        mime = clip.MimeData()
        mime.text = text
        mime["ExcludeClipboardContentFromMonitorProcessing"] = b"true"
        mime["org.nspasteboard.AutoGeneratedType"] = b"true"
        mime["org.nspasteboard.TransientType"] = b"true"
        clip.set_mime(mime)
    except (AttributeError, TypeError):
        clip.set_text(text)


def _parse_dictation_peek_response(
    raw_text: str, request_id: str, left: bool, right: bool
) -> tuple[Optional[str], Optional[str]]:
    """Validate and extract a response from the Emacs clipboard protocol."""
    try:
        response = json.loads(raw_text)
    except (TypeError, ValueError) as error:
        raise DictationPeekProtocolError("Emacs returned invalid JSON") from error

    if not isinstance(response, dict):
        raise DictationPeekProtocolError("Emacs returned a non-object response")
    if response.get("type") != DICTATION_PEEK_RESPONSE_TYPE:
        raise DictationPeekProtocolError("Emacs returned the wrong response type")
    if response.get("version") != DICTATION_PEEK_PROTOCOL_VERSION:
        raise DictationPeekProtocolError("Emacs returned an unsupported version")
    if response.get("requestId") != request_id:
        raise DictationPeekProtocolError("Emacs returned a mismatched request ID")
    if response.get("ok") is not True:
        message = response.get("error")
        if not isinstance(message, str) or not message:
            message = "unknown Emacs error"
        raise DictationPeekProtocolError(message)

    before = response.get("before")
    after = response.get("after")
    if left:
        if not isinstance(before, str):
            raise DictationPeekProtocolError("Emacs returned invalid left context")
    elif before is not None:
        raise DictationPeekProtocolError("Emacs returned unexpected left context")
    if right:
        if not isinstance(after, str):
            raise DictationPeekProtocolError("Emacs returned invalid right context")
    elif after is not None:
        raise DictationPeekProtocolError("Emacs returned unexpected right context")
    return before, after


def _is_dictation_peek_response_for_request(raw_text: str, request_id: str) -> bool:
    """Return whether RAW_TEXT is a tagged response for REQUEST_ID."""
    try:
        response = json.loads(raw_text)
    except (TypeError, ValueError):
        return False
    return (
        isinstance(response, dict)
        and response.get("type") == DICTATION_PEEK_RESPONSE_TYPE
        and response.get("version") == DICTATION_PEEK_PROTOCOL_VERSION
        and response.get("requestId") == request_id
    )


def _read_dictation_peek_response(
    request_id: str, left: bool, right: bool, timeout: float
) -> tuple[Optional[str], Optional[str]]:
    """Poll the clipboard until Emacs returns the matching response."""
    deadline = time.perf_counter() + timeout
    sleep_time = DICTATION_PEEK_MINIMUM_SLEEP_SECONDS
    last_error = None
    while True:
        raw_text = clip.text()
        if raw_text is not None:
            try:
                return _parse_dictation_peek_response(raw_text, request_id, left, right)
            except DictationPeekProtocolError as error:
                last_error = error
                # A matching response is authoritative, including a structured
                # Emacs error or invalid context values. Other clipboard values
                # may be the request itself or unrelated transient content.
                if _is_dictation_peek_response_for_request(raw_text, request_id):
                    raise

        time_left = deadline - time.perf_counter()
        if time_left <= 0:
            raise TimeoutError(
                "Timed out waiting for Emacs dictation context"
            ) from last_error
        actions.sleep(min(sleep_time, time_left))
        sleep_time = min(sleep_time * 2, time_left)


def _emacs_dictation_peek(
    left: bool, right: bool
) -> tuple[Optional[str], Optional[str]]:
    """Request dictation context from Emacs using one command invocation."""
    request_id = uuid.uuid4().hex
    request = json.dumps(
        {
            "type": DICTATION_PEEK_REQUEST_TYPE,
            "version": DICTATION_PEEK_PROTOCOL_VERSION,
            "requestId": request_id,
            "left": left,
            "right": right,
        },
        ensure_ascii=False,
        separators=(",", ":"),
    )
    timeout = settings.get("user.selected_text_timeout")
    with clip.revert():
        _set_transient_clipboard_text(request)
        actions.user.emacs("talon-dictation-peek")
        return _read_dictation_peek_response(request_id, left, right, timeout)


def _legacy_dictation_peek(
    left: bool, right: bool
) -> tuple[Optional[str], Optional[str]]:
    """Get Emacs context using the original marker and selection sequence."""
    before, after = None, None
    # Inserting a space ensures that there is something to select at the
    # beginning of a buffer. The space is removed before returning.
    actions.insert(" ")
    if left:
        # Select two words because one word is not enough around some
        # punctuation, such as the closing backtick in "`foo`".
        actions.edit.extend_word_left()
        actions.edit.extend_word_left()
        before = actions.edit.selected_text()[:-1]
        actions.user.emacs("pop-to-mark-command")
    if not right:
        actions.key("backspace")
    else:
        actions.edit.left()
        actions.edit.extend_word_right()
        actions.edit.extend_word_right()
        after = actions.edit.selected_text()[1:]
        actions.user.emacs("pop-to-mark-command")
        actions.key("delete")
    return before, after


def meta(keys):
    m = settings.get("user.emacs_meta")
    if m == "alt":
        return " ".join("alt-" + k for k in keys.split())
    elif m == "cmd":
        return " ".join("cmd-" + k for k in keys.split())
    elif m != "esc":
        logging.error(
            f"Unrecognized 'emacs_meta' setting: {m!r}. Falling back to 'esc'."
        )
    return "esc " + keys


def meta_fixup(k):
    if k.startswith("meta-"):
        k = meta(k[len("meta-") :])
    elif "meta-" in k:
        raise NotImplementedError("user.emacs_key(): please put meta- first")
    return k


@mod.action_class
class Actions:
    def emacs_meta(key: str):
        "Presses some keys modified by Emacs' meta key."
        actions.key(meta(key))

    def emacs_key(keys: str):
        """
        Presses some keys, translating 'meta-' prefix to the appropriate keys. For
        example, if the setting user.emacs_meta = 'esc', user.emacs_key("meta-ctrl-a")
        becomes key("esc ctrl-a").
        """
        actions.key(" ".join(meta_fixup(k) for k in keys.split()))

    def emacs_prefix(n: Optional[int] = None):
        "Inputs a prefix argument."
        if n is None:
            # `M-x universal-argument` doesn't have the same effect as pressing the key.
            prefix_key = actions.user.emacs_command_keybinding("universal-argument")
            actions.key(prefix_key or "ctrl-u")  # default to ctrl-u
        else:
            # Applying meta to each key can use fewer keypresses and 'works' in ansi-term
            # mode.
            actions.user.emacs_meta(" ".join(str(n)))

    def emacs(command_name: str, prefix: Optional[int] = None):
        """
        Runs the emacs command `command_name`. Defaults to using M-x, but may use
        a key binding if known or rpc if available. Provides numeric prefix argument
        `prefix` if specified.
        """
        meta_x = actions.user.emacs_command_keybinding("execute-extended-command")
        keys = actions.user.emacs_command_keybinding(command_name)
        if prefix is not None:
            actions.user.emacs_prefix(prefix)
        if keys is not None:
            actions.user.emacs_key(keys)
        else:
            actions.user.emacs_key(meta_x or "meta-x")
            actions.insert(command_name)
            actions.key("enter")

    def emacs_help(key: str = None):
        "Runs the emacs help command prefix, optionally followed by some keys."
        actions.key("ctrl-h")
        if key is not None:
            actions.key(key)

    # Line navigation and selection helpers.
    def jump_modulo_line(n: int):
        """Jumps to the nearest line number modulo 100."""
        actions.user.emacs("goto-modulo-line", n)

    def mark_lines(n1: int, n2: int = -1, tight: bool = False, tree: bool = False):
        """Marks the lines from n1 to n2."""
        actions.user.jump_modulo_line(n1)
        if tree:
            actions.user.emacs("org-mark-element")
            return
        if tight:
            actions.user.emacs("back-to-indentation")
        actions.user.emacs("set-mark-command")
        if n2 != -1:
            actions.user.jump_modulo_line(n2)
        if tight:
            actions.user.emacs("move-end-of-line")
        else:
            actions.user.emacs("next-line")

    def use_lines(
        n1: int,
        n2: int = -1,
        copy: bool = False,
        tight: bool = False,
        other_buffer: bool = False,
        tree: bool = False,
    ):
        """Copies or moves lines to the current position."""
        if other_buffer:
            actions.user.emacs("other-window")
        else:
            actions.user.emacs("push-mark-no-activate")

        actions.user.mark_lines(n1, n2, tight, tree)
        actions.user.emacs("kill-ring-save" if copy else "kill-region")
        actions.user.emacs("jump-to-mark")

        if other_buffer:
            actions.user.emacs("other-window")
        else:
            actions.user.emacs("jump-to-mark")
        if not tight and not tree:
            actions.user.emacs("move-beginning-of-line")
        actions.user.emacs("org-paste-special" if tree else "yank")


@ctx.action_class("user")
class UserActions:
    def cut_line():
        actions.edit.line_start()
        actions.user.emacs("kill-line", 1)

    def split_window():
        actions.user.emacs("split-window-right")

    def split_window_vertically():
        actions.user.emacs("split-window-right")

    def split_window_up():
        actions.user.emacs("split-window-below")

    def split_window_down():
        actions.user.emacs("split-window-below")
        actions.user.emacs("other-window")

    def split_window_horizontally():
        actions.user.emacs("split-window-below")

    def split_window_left():
        actions.user.emacs("split-window-right")

    def split_window_right():
        actions.user.emacs("split-window-right")
        actions.user.emacs("other-window")

    def split_clear():
        actions.user.emacs("delete-window")

    def split_clear_all():
        actions.user.emacs("delete-other-windows")

    def split_reset():
        actions.user.emacs("balance-windows")

    def split_next():
        actions.user.emacs("other-window")

    def split_last():
        actions.user.emacs("other-window", -1)

    def split_flip():
        # only works reliably if there are only two panes/windows.
        actions.key("ctrl-x b enter ctrl-x o ctrl-x b enter")
        actions.user.split_last()
        actions.key("ctrl-x b enter ctrl-x o")

    def select_range(line_start, line_end):
        # Assumes transient mark mode.
        actions.edit.jump_line(line_start)
        actions.edit.jump_line(line_end + 1)
        actions.user.emacs("exchange-point-and-mark")

    def tab_jump(number: int):
        actions.user.emacs("tab-select", number)

    def tab_final():
        actions.user.emacs("tab-last")

    # # Version that highlights without transient-mark-mode:
    # def select_range(line_start, line_end):
    #     actions.edit.jump_line(line_end + 1)
    #     actions.key("ctrl-@ ctrl-@")
    #     actions.edit.jump_line(line_start)

    def dictation_peek(left: bool, right: bool) -> tuple[Optional[str], Optional[str]]:
        if not (left or right):
            return None, None
        try:
            return _emacs_dictation_peek(left, right)
        except Exception:
            logging.warning(
                "Fast Emacs dictation peek failed; falling back to selections",
                exc_info=True,
            )
            return _legacy_dictation_peek(left, right)


@ctx.action_class("edit")
class EditActions:
    def save():
        actions.user.emacs("save-buffer")

    def save_all():
        actions.user.emacs("save-some-buffers")

    def copy():
        actions.user.emacs("kill-ring-save")
        # Restore the active region and its original direction after copying.
        actions.user.emacs("exchange-point-and-mark")
        actions.user.emacs("exchange-point-and-mark")

    def cut():
        actions.user.emacs("kill-region")

    def undo():
        actions.user.emacs("undo")

    def paste():
        # Keep this as a physical key so paste-to-insert can call edit.paste()
        # without recursively re-entering user.emacs() while it types an M-x
        # command name.
        actions.key("ctrl-y")

    def paste_match_style():
        actions.key("ctrl-y")

    def redo():
        actions.user.emacs("undo-redo")

    def delete():
        actions.user.emacs("kill-region")

    def file_start():
        actions.user.emacs("beginning-of-buffer")

    def file_end():
        actions.user.emacs("end-of-buffer")

    # These commands push the original point to the mark but leave the region
    # inactive. Exchange twice to reactivate it without changing direction.
    def extend_file_start():
        actions.user.emacs("beginning-of-buffer")
        actions.user.emacs("exchange-point-and-mark")
        actions.user.emacs("exchange-point-and-mark")

    def extend_file_end():
        actions.user.emacs("end-of-buffer")
        actions.user.emacs("exchange-point-and-mark")
        actions.user.emacs("exchange-point-and-mark")

    def select_none():
        actions.user.emacs("keyboard-quit")

    def select_all():
        actions.user.emacs("mark-whole-buffer")
        # If you don't use transient-mark-mode, maybe do this:
        # actions.key('ctrl-u ctrl-x ctrl-x')

    def word_left():
        actions.user.emacs("backward-word")

    def word_right():
        actions.user.emacs("forward-word")

    def sentence_start():
        actions.user.emacs("backward-sentence")

    def sentence_end():
        actions.user.emacs("forward-sentence")

    def extend_sentence_start():
        actions.user.emacs_meta("shift-a")

    def extend_sentence_end():
        actions.user.emacs_meta("shift-e")

    def paragraph_start():
        actions.user.emacs("backward-paragraph")

    def paragraph_end():
        actions.user.emacs("forward-paragraph")

    def line_start():
        actions.user.emacs("move-beginning-of-line")

    def line_end():
        actions.user.emacs("move-end-of-line")

    def line_swap_down():
        actions.user.emacs("move-text-down")

    def line_swap_up():
        actions.user.emacs("move-text-up")

    def delete_line():
        actions.key("ctrl-a ctrl-k")

    def line_clone():
        actions.user.emacs("copy-text-down")

    def jump_line(n):
        actions.user.emacs("goto-line", n)

    def select_line(n=None):
        if n is not None:
            actions.edit.jump_line(n)
        else:
            actions.edit.line_start()
        actions.edit.extend_line_end()
        actions.edit.extend_right()
        # This makes it so the cursor is on the same line, which can make
        # subsequent commands more convenient.
        actions.user.emacs("exchange-point-and-mark")

    def indent_more():
        actions.user.emacs("indent-rigidly")
        actions.key("shift-right")

    def indent_less():
        actions.user.emacs("indent-rigidly")
        actions.key("shift-left")

    # These all perform text-scale-adjust, which examines the actual key pressed, so can't
    # be done with actions.user.emacs.
    def zoom_in():
        actions.key("ctrl-x ctrl-+")

    def zoom_out():
        actions.key("ctrl-x ctrl--")

    def zoom_reset():
        actions.key("ctrl-x ctrl-0")

    # Some modes override ctrl-s/r to do something other than isearch-forward, so we
    # deliberately don't use actions.user.emacs.
    def find(text=None):
        actions.key("ctrl-s")
        if text:
            actions.insert(text)

    def find_next():
        actions.key("ctrl-s")

    def find_previous():
        actions.key("ctrl-r")


@ctx.action_class("app")
class AppActions:
    def window_open():
        actions.user.emacs("make-frame-command")

    def tab_next():
        actions.user.emacs("tab-next")

    def tab_previous():
        actions.user.emacs("tab-previous")

    def tab_close():
        actions.user.emacs("tab-close")

    def tab_reopen():
        actions.user.emacs("tab-undo")

    def tab_open():
        actions.user.emacs("tab-new")


@ctx.action_class("code")
class CodeActions:
    def toggle_comment():
        actions.user.emacs("comment-dwim")

    def language():
        # Assumes win.filename() gives buffer name.
        if actions.win.filename() == "*scratch*":
            return "elisp"
        return actions.next()


@ctx.action_class("win")
class WinActions:
    # This assumes the title either is the buffer name or contains the buffer
    # name before a space-surrounded hyphen. This is the default for the latest
    # GNU Emacs. If you are not on macOS and your flavor of Emacs defaults to
    # something incompatible, you may need to put one of the following two
    # declarations into your init.el ("%b" being replaced by the buffer name):
    # (setq frame-title-format "%b")
    # (setq frame-title-format '(multiple-frames "%b" ("" "%b - Emacs at " system-name)))
    def filename():
        # On macOS, get the filename directly
        if doc := getattr(ui.active_window(), "doc", None):
            return doc

        # Otherwise, get it from the window title
        title = actions.win.title()
        buffer_name = title.split(" - ")[0]
        return re.sub(r"<[^>]+>$", "", buffer_name)
